"""What `mount_egress_tables` promises about shape, prefixes and isolation (ADR-0050).

The development plan names two likely failure modes for this phase, and both are defended against
structurally here rather than noticed later: *index names colliding without the prefix* (the
two-prefixes-one-metadata test), and *dialect-specific storage* — here that means an enum column,
not an integer width, since this table has nothing to accumulate (the portable-column-types test
and the enum-as-text test, with the host's autogenerated revision checked in ``test_hostapp.py``).
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql
import sqlalchemy.dialects.sqlite
from baseaicore import DataClassification

from commissioner import EgressRequest, EgressTarget, Verdict
from commissioner.policy import OrderedClassificationPolicy
from commissioner.sql import DEFAULT_TABLE_PREFIX, SqlEgressLedger, mount_egress_tables
from conftest import ManualClock, mounted, session_factory_for

if TYPE_CHECKING:
    from sqlalchemy import Engine

PORTABLE_TYPES = {"String", "Text", "DateTime"}
"""Every column type this table is allowed to use.

Deliberately small, and all three are SQLAlchemy *generic* types. A generic type renders per
dialect and Alembic renders it back as ``sa.<Name>()``, so the host's autogenerated revision runs
unchanged on both. A type imported from ``sqlalchemy.dialects.*`` — ``JSONB``, ``UUID``, a
PostgreSQL ``ENUM`` — renders into the revision as ``postgresql.JSONB()`` and takes the host's
migration history with it onto one dialect.
"""


def test_the_default_prefix_is_the_documented_one() -> None:
    tables = mount_egress_tables(sa.MetaData())
    assert DEFAULT_TABLE_PREFIX == "egress_"
    assert [table.name for table in tables.all_tables] == ["egress_decisions"]


def test_two_prefixes_mount_into_one_metadata_without_colliding() -> None:
    """The concrete form of "index names colliding without the prefix".

    One ``MetaData`` is what a host has. If a second mount reused an index or constraint name, this
    would raise here — and on PostgreSQL, where index names are unique per schema, it would raise
    at ``upgrade`` time in production instead.
    """
    metadata = sa.MetaData()
    first = mount_egress_tables(metadata, prefix="egress_")
    second = mount_egress_tables(metadata, prefix="trial_")

    every_name: list[str] = []
    for tables in (first, second):
        names: list[str] = []
        for table in tables.all_tables:
            names.append(table.name)
            names.extend(str(index.name) for index in table.indexes)
            names.extend(str(constraint.name) for constraint in table.constraints)
        every_name.extend(names)
        for name in names:
            bare = name.removeprefix("pk_").removeprefix("ix_")
            assert bare.startswith(tables.prefix), f"{name} does not carry {tables.prefix!r}"
    assert len(every_name) == len(set(every_name)), sorted(every_name)


def test_mounting_the_same_prefix_twice_into_one_metadata_is_refused() -> None:
    metadata = sa.MetaData()
    mount_egress_tables(metadata)
    with pytest.raises(sa.exc.InvalidRequestError, match="already defined"):
        mount_egress_tables(metadata)


@pytest.mark.parametrize("prefix", ["", "1egress_", "egress-", "egress table_", "ëgress_"])
def test_a_prefix_that_is_not_an_identifier_is_refused(prefix: str) -> None:
    with pytest.raises(ValueError, match="prefix"):
        mount_egress_tables(sa.MetaData(), prefix=prefix)


def test_every_column_type_is_portable_across_both_dialects() -> None:
    tables = mount_egress_tables(sa.MetaData())
    sqlite = sa.dialects.sqlite.dialect()
    postgresql = sa.dialects.postgresql.dialect()  # type: ignore[no-untyped-call] # SQLAlchemy
    for table in tables.all_tables:
        for column in table.columns:
            kind = type(column.type)
            where = f"{table.name}.{column.name}"
            assert kind.__module__ == "sqlalchemy.sql.sqltypes", (
                f"{where} uses {kind.__module__}.{kind.__name__}, which is dialect-specific and "
                "would render into a host's autogenerated revision as such"
            )
            assert kind.__name__ in PORTABLE_TYPES, f"{where} is {kind.__name__}"
            # And both dialects can actually render DDL for it.
            assert column.type.compile(sqlite)
            assert column.type.compile(postgresql)


def test_the_verdict_column_is_a_plain_string_not_a_native_enum() -> None:
    """The development plan's named failure mode: dialect-specific enum storage.

    ``sa.Enum`` creates a native ``ENUM`` type on PostgreSQL and a ``CHECK`` constraint on SQLite —
    the same code producing two schemas. This asserts the column is exactly ``String``.
    """
    tables = mount_egress_tables(sa.MetaData())
    column = tables.decisions.c.verdict
    assert isinstance(column.type, sa.String)
    assert not isinstance(column.type, sa.Enum)


def test_no_foreign_key_leaves_the_mounted_set() -> None:
    """ADR-0050 decision 2: no relationship to an application's entities, in either direction."""
    tables = mount_egress_tables(sa.MetaData())
    for table in tables.all_tables:
        assert table.foreign_keys == set()


def test_the_handle_points_at_the_metadata_the_host_passed() -> None:
    metadata = sa.MetaData()
    tables = mount_egress_tables(metadata, prefix="audit_")
    assert tables.metadata is metadata
    assert tables.prefix == "audit_"
    assert set(metadata.tables) == {table.name for table in tables.all_tables}


def test_the_table_creates_and_round_trips_on_both_dialects(engine: Engine) -> None:
    _, tables = mounted(engine, prefix="audit_")
    inspector = sa.inspect(engine)
    assert set(inspector.get_table_names()) >= {table.name for table in tables.all_tables}

    ledger = SqlEgressLedger(session_factory_for(engine), table_prefix="audit_")
    # The ledger builds its statements against the same shape, under the same prefix.
    assert ledger.tables.prefix == "audit_"
    assert [table.name for table in ledger.tables.all_tables] == [
        table.name for table in tables.all_tables
    ]

    policy = OrderedClassificationPolicy(clock=ManualClock())
    decision = policy.evaluate(
        EgressRequest(
            run_id="traj-1",
            source_ref="turn-1",
            data_classification=DataClassification.PUBLIC,
            target=EgressTarget(name="local", remote=False),
        )
    )
    ledger.record(decision)
    assert ledger.decisions(run_id="traj-1")[0].verdict is Verdict.APPROVED


def test_two_hosts_two_databases_one_package_version_do_not_see_each_other(
    tmp_path_factory: pytest.TempPathFactory,
) -> None:
    """ "Two applications mounting this table have two tables in two databases — never one."

    Different prefixes *and* different files, because both are how a host keeps its ledger its
    own: the prefix separates them inside one schema, the file separates the schemas.
    """
    directory = tmp_path_factory.mktemp("two-hosts")
    ledgers = {}
    engines = {}
    for name, prefix in (("alpha", "egress_"), ("beta", "audit_")):
        engine = sa.create_engine(f"sqlite:///{directory / f'{name}.sqlite3'}")
        engines[name] = engine
        mounted(engine, prefix=prefix)
        ledgers[name] = SqlEgressLedger(session_factory_for(engine), table_prefix=prefix)

    policy = OrderedClassificationPolicy(clock=ManualClock())
    decision = policy.evaluate(
        EgressRequest(
            run_id="shared-run-id",
            source_ref="turn-1",
            data_classification=DataClassification.PUBLIC,
            target=EgressTarget(name="local", remote=False),
        )
    )
    ledgers["alpha"].record(decision)

    assert len(ledgers["alpha"].decisions(run_id="shared-run-id")) == 1
    assert len(ledgers["beta"].decisions(run_id="shared-run-id")) == 0
    for name in engines:
        engines[name].dispose()


def test_the_package_creates_no_table_of_its_own_on_import() -> None:
    """No ``create_all`` in library code, ever (ADR-0050 decision 5).

    Reading the source is the only way to assert the absence of a call that would otherwise only
    show up as a table appearing in someone's database.
    """
    import ast
    from pathlib import Path

    import commissioner

    forbidden = {"create_all", "create_engine", "getenv", "environ", "connect", "run_migrations"}
    source_root = Path(str(commissioner.__file__)).parent
    called: set[str] = set()
    for module in sorted(source_root.glob("*.py")):
        tree = ast.parse(module.read_text(encoding="utf-8"), filename=str(module))
        for node in ast.walk(tree):
            if isinstance(node, ast.Attribute) and node.attr in forbidden:
                called.add(f"{module.name}:{node.attr}")
            if isinstance(node, ast.Name) and node.id in forbidden:
                called.add(f"{module.name}:{node.id}")
    assert called == set(), (
        f"library code reaches for {sorted(called)} — the package owns no engine, no connection, "
        "no environment and no migration (ADR-0050 decisions 3 and 5)"
    )
