"""The shipped policy's whole behaviour: four rows, exhaustive over the enums (spec §18, §20.1).

The classification × target matrix is generated from :class:`~baseaicore.DataClassification`'s
own members and a fixed list of target shapes, never hand-listed as fifteen separate cases — a
hand-written list is the same test with a hole in it (development plan, Phase 1 acceptance
criterion 1).

The expected verdict is computed here from an independently-stated ordering (``_ORDER.index``),
not from :class:`~baseaicore.DataClassification`'s own ``<=`` operator — the same operator the
policy uses internally. Testing "does the policy wire the four-row rule correctly" against a
second, independent statement of the ordering is what makes this matrix worth more than a mirror
of the implementation.
"""

from __future__ import annotations

import itertools
import random

import pytest
from baseaicore import DataClassification

from conftest import MIDDAY, ManualClock
from spotcheck import (
    EgressDecision,
    EgressPolicy,
    EgressRequest,
    EgressTarget,
    OrderedClassificationPolicy,
    Verdict,
)

_ORDER = (DataClassification.PUBLIC, DataClassification.INTERNAL, DataClassification.CONFIDENTIAL)
"""ADR-0046's ordering, restated independently of `DataClassification.__le__`."""

_TARGET_SHAPES = (
    "local",
    "remote_no_ceiling",
    "remote_ceiling_public",
    "remote_ceiling_internal",
    "remote_ceiling_confidential",
)


def _target(shape: str) -> EgressTarget:
    """Build one of the five target shapes the matrix covers."""
    if shape == "local":
        return EgressTarget(name="ollama-local", remote=False)
    if shape == "remote_no_ceiling":
        return EgressTarget(name="remote-unbounded", remote=True)
    ceiling = {
        "remote_ceiling_public": DataClassification.PUBLIC,
        "remote_ceiling_internal": DataClassification.INTERNAL,
        "remote_ceiling_confidential": DataClassification.CONFIDENTIAL,
    }[shape]
    return EgressTarget(
        name=f"remote-{ceiling.value}", remote=True, max_data_classification=ceiling
    )


def _expected(classification: DataClassification, shape: str) -> tuple[Verdict, str]:
    """Return the documented ``(verdict, reason)`` pair for one matrix cell (ADR-0054 rule 2)."""
    if shape == "local":
        return Verdict.APPROVED, "target_not_remote"
    if shape == "remote_no_ceiling":
        return Verdict.DENIED, "no_ceiling_declared"
    ceiling = _target(shape).max_data_classification
    assert ceiling is not None
    if _ORDER.index(classification) <= _ORDER.index(ceiling):
        return Verdict.APPROVED, "within_ceiling"
    return Verdict.DENIED, "classification_exceeds_ceiling"


_MATRIX = list(itertools.product(DataClassification, _TARGET_SHAPES))


class TestFullMatrix:
    @pytest.mark.parametrize(
        ("classification", "shape"), _MATRIX, ids=[f"{c.value}-{s}" for c, s in _MATRIX]
    )
    def test_every_cell_matches_the_documented_rule(
        self, classification: DataClassification, shape: str, clock: ManualClock
    ) -> None:
        policy = OrderedClassificationPolicy(clock=clock)
        request = EgressRequest(
            run_id="traj-1",
            source_ref="turn-1",
            data_classification=classification,
            target=_target(shape),
        )
        decision = policy.evaluate(request)
        expected_verdict, expected_reason = _expected(classification, shape)
        assert (decision.verdict, decision.reason) == (expected_verdict, expected_reason)

    def test_the_matrix_covers_every_classification_and_every_shape(self) -> None:
        # A change to either enum silently widens or narrows this matrix; this assertion is what
        # makes that visible instead of the parametrization quietly running fewer cases.
        assert {c for c, _ in _MATRIX} == set(DataClassification)
        assert {s for _, s in _MATRIX} == set(_TARGET_SHAPES)
        assert len(_MATRIX) == len(DataClassification) * len(_TARGET_SHAPES)

    @pytest.mark.parametrize(
        ("classification", "shape"), _MATRIX, ids=[f"{c.value}-{s}" for c, s in _MATRIX]
    )
    def test_the_shipped_policy_never_produces_violation(
        self, classification: DataClassification, shape: str, clock: ManualClock
    ) -> None:
        # ADR-0054 rule 7: VIOLATION is writable but never generated by OrderedClassificationPolicy.
        policy = OrderedClassificationPolicy(clock=clock)
        request = EgressRequest(
            run_id="traj-1",
            source_ref="turn-1",
            data_classification=classification,
            target=_target(shape),
        )
        assert policy.evaluate(request).verdict != Verdict.VIOLATION


class TestDeterminism:
    """Spec §11 contract 3: same request, same policy version -> identical decision."""

    def _decide(self, *, seed: int) -> EgressDecision:
        policy = OrderedClassificationPolicy(
            clock=ManualClock(MIDDAY),
            randomness_source=random.Random(seed),  # noqa: S311 — reproducibility, not security
        )
        request = EgressRequest(
            run_id="traj-1",
            source_ref="turn-3",
            data_classification=DataClassification.INTERNAL,
            target=EgressTarget(
                name="tools.plan.remote_cheap",
                remote=True,
                max_data_classification=DataClassification.INTERNAL,
                provider_kind="openai_compatible",
            ),
        )
        return policy.evaluate(request)

    def test_two_fresh_policies_with_the_same_clock_and_seed_agree_exactly(self) -> None:
        assert self._decide(seed=42) == self._decide(seed=42)

    def test_a_different_seed_still_agrees_on_everything_but_the_id(self) -> None:
        first, second = self._decide(seed=1), self._decide(seed=2)
        assert first != second
        assert first.decision_id != second.decision_id
        assert (first.verdict, first.reason, first.decided_at) == (
            second.verdict,
            second.reason,
            second.decided_at,
        )


def test_policy_reports_its_own_name_and_version(clock: ManualClock) -> None:
    policy = OrderedClassificationPolicy(clock=clock)
    assert (policy.name, policy.version) == ("OrderedClassificationPolicy", "1.0")


def test_policy_satisfies_the_egress_policy_protocol(clock: ManualClock) -> None:
    assert isinstance(OrderedClassificationPolicy(clock=clock), EgressPolicy)
